### ISSUE TITLE
Could not boot up

### ISSUE THREAD

**Issue by 3cp** [Bitcadia/Bitcadia#5]
I could not even boot up the app on my mac.

I guess your customised tasks only works on windows, as I got lots of files like this `scripts\app.js` (one file, not folder+file) in my project folder.

I think you can just use `/` to join your file parts, it should work on windows too. The another better way is to use `path.join(part0, part1, part2)` to handle file path generation.

**Comment by huochunpeng** [comment]
If you want to debug the html rebuild issue on your PC.

Edit `node_modules/aurelia-cli/lib/build/bundled-source.js`, add two lines after logger.debug at line 117

```js
logger.debug(`Tracing ${moduleId}`);
// use stringily to show unexpected chars if there is any
console.log('modulePath: ' + JSON.stringify(modulePath));
console.log('ext: ' + JSON.stringify(path.extname(modulePath)));
```

Let me know the last console log on modulePath and ext, just above your html rebuild error. Thx.

**Comment by huochunpeng** [comment]
Even that the app is not working, I can still reproduce the rebuild issue in console. Working on it.

**Comment by huochunpeng** [comment]
The rebuild issue is caused by this line:

https://github.com/Bitcadia/Bitcadia/blob/73ea89d11dcee0f37d74c9d966494e90af557571/aurelia_project/tasks/modual-build.ts#L267

It cleared requirejs text plugins (text plugin) to handle the .html resources, so it tried to load the html file as normal js module.

Why you do that clearance?

**Comment by huochunpeng** [comment]
@DrSammyD
